apiVersion: v1
kind: Pod
metadata:
  name: dockerdemo
  labels:
    app: web
spec:
  containers:
    - name: dockerdemo
      image: msregistrytest.azurecr.io/nidhi5885/dockerv7:2
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: mysecret