apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerappdemo1
spec:
  selector:
    matchLabels:
      run: dockerappdemo1
  replicas: 1
  template:
    metadata:
      labels:
        run: dockerappdemo1
    spec:
      containers:
      - name: dockerappdemo1
        image: msregistrytest.azurecr.io/nidhi5885/dockerv7:2
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mysecret

---

apiVersion: v1
kind: Service
metadata:
  name: dockerappdemo1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dockerappdemo1
