apiVersion: v1
kind: Pod
metadata:
  name: dockerappdemo
  labels:
    app: web
spec:
  containers:
    - name: dockerappdemo
      image: msregistrytest.azurecr.io/nidhi5885/dockerv7:2
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: mysecret
  
---

apiVersion: v1
kind: Service
metadata:
  name: dockerappdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dockerappdemo
